services:
  nestjs_https:
    container_name: nestjs_https
    build: .
    ports:
      - '3330:3001'
    networks:
      - nestjs-net

  postgres:
    container_name: postgres-container
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydatabase
    ports:
      - "5555:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - nestjs-net

networks:
  nestjs-net:

volumes:
  postgres-data: